"""
Gemini LLM provider implementation.
"""

from typing import Iterator
from google import genai
from .provider import LLMProvider


class GeminiProvider(LLMProvider):
    """
    Gemini API provider using google-genai SDK.

    Supports both normal and streaming generation through Gemini's
    native APIs.
    """

    def __init__(self, api_key: str, model: str = "gemini-2.5-flash"):
        """
        Initialize Gemini provider.

        Args:
            api_key: Gemini API key
            model: Model identifier (default: gemini-2.5-flash)
        """
        self.client = genai.Client(api_key=api_key)
        self.model = model

    def generate(self, prompt: str) -> str:
        """
        Generate a complete response using Gemini.

        Args:
            prompt: The prompt text

        Returns:
            Complete generated text

        Raises:
            Exception: If Gemini API call fails
        """
        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt
        )
        return response.text

    def generate_stream(self, prompt: str) -> Iterator[str]:
        """
        Generate a streaming response using Gemini's native streaming.

        Uses generate_content_stream() for true token-by-token streaming.

        Args:
            prompt: The prompt text

        Yields:
            Text chunks as they are generated by Gemini

        Raises:
            Exception: If Gemini API call fails
        """
        response = self.client.models.generate_content_stream(
            model=self.model,
            contents=prompt
        )

        for chunk in response:
            if chunk.text:
                yield chunk.text
